const SET_TOKEN = 'SET_TOKEN'
const RESET_TOKEN = 'RESET_TOKEN'

const ADD_PRODUCT = 'ADD_PRODUCT'
const REMOVE_PRODUCT = 'REMOVE_PRODUCT'

const SET_CART_ITEM = 'SET_CART_ITEM'
const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM'

const ADD_ORDER = 'ADD_ORDER'
const REMOVE_ORDER = 'REMOVE_ORDER'

const ADD_CUSTOMER = 'ADD_CUSTOMER'
const REMOVE_CUSTOMER = 'REMOVE_CUSTOMER'

const ADD_ADDRESS = 'ADD_ADDRESS'
const REMOVE_ADDRESS = 'REMOVE_ADDRESS'

export { SET_TOKEN, RESET_TOKEN, 
    ADD_PRODUCT, REMOVE_PRODUCT, 
    SET_CART_ITEM, REMOVE_CART_ITEM,
    ADD_ORDER, REMOVE_ORDER,
    ADD_CUSTOMER, REMOVE_CUSTOMER,
    ADD_ADDRESS, REMOVE_ADDRESS }